version: '3.9'
services:   
  deriv_ui_dev_nginx:
      restart: "on-failure"
      build: 
        dockerfile: Dockerfile.dev
        context: ./nginx
      ports:
        - 2005:80
      depends_on:
        - deriv_ui_dev

  deriv_ui_dev:
    build: 
      dockerfile: Dockerfile.dev
      context: .
    volumes:
      - ./:/app
    ports:
      - 3000:3000
      

   

  

