FROM node:16-alpine as builder

WORKDIR '/app'

COPY package.json ./
COPY yarn.lock ./
COPY tsconfig.json ./

RUN yarn install --ignore-engines --ignore-platform

COPY . . 

RUN yarn build:dev

FROM nginx
EXPOSE 3000
COPY ./nginx/default.dev.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/build /usr/share/nginx/html