import { Tabs as AntdTabs } from "antd";
import { Radio as AntdRadio } from "antd";
import { Layout as AntdLayout } from "antd";
import { Table as AntdTable } from "antd";
import { Spin as AntdSpin } from "antd";
import { Button as AntdButton } from "antd";
import { Space as AntdSpace } from "antd";
import { Result as AntdResult } from "antd";
import { Typography } from 'antd';

export const Tabs = AntdTabs;
export const TabPane = Tabs.TabPane;
export const Layout = AntdLayout;
export const Content = Layout.Content;
export const RadioGroup = AntdRadio.Group;
export const Spin = AntdSpin;
export const Button = AntdButton;
export const Result = AntdResult;
export const Space = AntdSpace;
export const Table = AntdTable;
export const Title = Typography.Title;
export const Text = Typography.Text;
